import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/globals.css";
import Navbar from "../components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col bg-space-black justify-center items-center">
          <div className="w-4/6 bg-space-black overflow-y-auto">
            <Navbar></Navbar>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
